name: Create Package
"on":
    push:
        branches: "oupsy"
jobs:
    create-package:
        name: Fix latest
        runs-on:
            - ubuntu-latest
        steps:
            - name: Docker login gcr.io
              if: ${{ (github.event_name != 'pull_request' || ! github.event.pull_request.head.repo.fork) && (github.actor != 'dependabot[bot]') }}
              uses: docker/login-action@v3
              with:
                password: ${{ secrets.GCR_PUSH_BOT_JSON_KEY }}
                registry: gcr.io
                username: _json_key
            - name: Docker login docker.io
              if: ${{ (github.event_name != 'pull_request' || ! github.event.pull_request.head.repo.fork) && (github.actor != 'dependabot[bot]') }}
              uses: docker/login-action@v3
              with:
                password: ${{ secrets.PAKETO_BUILDPACKS_DOCKERHUB_PASSWORD }}
                registry: docker.io
                username: ${{ secrets.PAKETO_BUILDPACKS_DOCKERHUB_USERNAME }}
            - uses: actions/setup-go@v5
              with:
                go-version: "1.20"
            - name: Install create-package
              run: |
                #!/usr/bin/env bash

                set -euo pipefail

                go install -ldflags="-s -w" github.com/paketo-buildpacks/libpak/cmd/create-package@latest
            - uses: buildpacks/github-actions/setup-tools@v5.5.3
              with:
                crane-version: 0.19.0
                yj-version: 5.1.0
            - name: revert latest
              run: |
                crane tag docker.io/paketobuildpacks/java-native-image:9.1.0 latest
                crane tag gcr.io/paketo-buildpacks/java-native-image:9.1.0 latest
