name: Update Draft Release
"on":
    push:
        branches:
            - main
jobs:
    update:
        name: Update Draft Release
        runs-on:
            - ubuntu-latest
        steps:
            - id: release-drafter
              uses: release-drafter/release-drafter@v5
              env:
                GITHUB_TOKEN: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
            - name: Docker login gcr.io
              if: ${{ (github.event_name != 'pull_request' || ! github.event.pull_request.head.repo.fork) && (github.actor != 'dependabot[bot]') }}
              uses: docker/login-action@v3
              with:
                password: ${{ secrets.GCR_PUSH_BOT_JSON_KEY }}
                registry: gcr.io
                username: _json_key
            - name: Docker login docker.io
              if: ${{ (github.event_name != 'pull_request' || ! github.event.pull_request.head.repo.fork) && (github.actor != 'dependabot[bot]') }}
              uses: docker/login-action@v3
              with:
                password: ${{ secrets.PAKETO_BUILDPACKS_DOCKERHUB_PASSWORD }}
                registry: docker.io
                username: ${{ secrets.PAKETO_BUILDPACKS_DOCKERHUB_USERNAME }}
            - uses: actions/checkout@v4
            - name: Update draft release with buildpack information
              uses: docker://ghcr.io/paketo-buildpacks/actions/draft-release:main
              with:
                github_token: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
                release_body: ${{ steps.release-drafter.outputs.body }}
                release_id: ${{ steps.release-drafter.outputs.id }}
                release_name: ${{ steps.release-drafter.outputs.name }}
                release_tag_name: ${{ steps.release-drafter.outputs.tag_name }}
